In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append("../../eqnet")
sys.path.append("..")

In [2]:
from expemb.data.dataset import ExpressionTreeTupleDataset
from expemb import SemVecTokenizer

tokenizer = SemVecTokenizer()
dataset = ExpressionTreeTupleDataset("../data/semvec/boolean10.train.gz", tokenizer)

/home/gangwar2/.miniconda/envs/expembtx/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Reading -1 training examples from ../data/semvec/boolean10.train.gz
Skipped 0 lines due to max sequence length restriction.


In [3]:
dataset[0]

(tensor([15, 18, 17,  7,  6, 18, 17,  6, 17,  5]),
 [[8, 9], [6, 7], [5, 6], [5, 8], [2, 3], [1, 2], [1, 4], [0, 1], [0, 5]],
 array([3, 2, 1, 0, 0, 2, 1, 0, 1, 0]),
 array([1, 1, 2, 2, 1, 2, 2, 3, 3]),
 tensor([ 0, 15, 18,  7,  5, 17, 18, 16,  7,  7,  6,  1]))

In [38]:
tokenizer.decode(dataset[0][-1])

'SOE and xor b a not xor or b b c EOE'

In [4]:
from torch.utils.data import DataLoader

In [14]:
dataloader = DataLoader(dataset, batch_size = 8, collate_fn = dataset.collate_fn)

In [15]:
next(iter(dataloader))

({'features': tensor([15, 18, 17,  7,  6, 18, 17,  6, 17,  5, 15, 18,  7,  5, 17, 18, 16,  7,
           7,  6, 15, 18, 17,  6,  7, 18, 16,  7,  7,  5, 17, 19, 18,  5, 16,  6,
           6, 18,  6,  7, 15, 18, 15,  6,  6,  5, 18, 17,  6,  7, 17, 19, 18,  6,
           5, 18,  7, 16,  6,  6, 17, 19, 18,  7,  5, 17, 17, 18,  6,  7, 17, 19,
          18,  6, 15,  5,  5, 18,  7,  6]),
  'node_order': tensor([3, 2, 1, 0, 0, 2, 1, 0, 1, 0, 4, 1, 0, 0, 3, 2, 1, 0, 0, 0, 3, 2, 1, 0,
          0, 2, 1, 0, 0, 0, 4, 3, 2, 0, 1, 0, 0, 1, 0, 0, 3, 2, 1, 0, 0, 0, 2, 1,
          0, 0, 4, 3, 1, 0, 0, 2, 0, 1, 0, 0, 5, 4, 1, 0, 0, 3, 2, 1, 0, 0, 4, 3,
          2, 0, 1, 0, 0, 1, 0, 0]),
  'edge_order': tensor([1, 1, 2, 2, 1, 2, 2, 3, 3, 1, 1, 2, 2, 3, 1, 1, 4, 4, 1, 1, 2, 2, 1, 2,
          2, 3, 3, 1, 1, 1, 1, 2, 2, 3, 3, 4, 1, 2, 2, 1, 1, 2, 2, 3, 3, 1, 1, 2,
          2, 1, 1, 3, 3, 4, 1, 1, 2, 3, 1, 1, 4, 4, 5, 1, 1, 1, 1, 2, 2, 3, 3, 4]),
  'adjacency_list': tensor([[ 8,  9],
          [ 6,  7],


In [30]:
a = [1, 2, 3]

In [32]:
for idx, elem in reversed(list(enumerate(a))):
    print(idx, elem)

2 3
1 2
0 1


In [19]:
a = torch.tensor([5, 2, 6], dtype = torch.long)

import torch

torch.arange(max(a))[None, :] < a[:, None]

tensor([[ True,  True,  True,  True,  True, False],
        [ True,  True, False, False, False, False],
        [ True,  True,  True,  True,  True,  True]])

In [17]:
a[:, 

TypeError: list indices must be integers or slices, not tuple